#!/usr/bin/env bash

die() {

  >&2 echo "$@"
  exit 1

}

figlol() {

  local text=$1
  figlet -w "$(tput cols)" -c "$text" | lolcat

}

set-tmux() {

  tmux set-option -g automatic-rename off

}

showtitle() {

  local main=$1
  local sub=$2

  clear
  figlol "$main"
  figlol "$sub"

  read -r

}

splash() {

  showtitle "mock" "$(basename "$PWD")"

}
