#!/usr/bin/env bash

set -o pipefail

HERE="$(dirname "$0")"
source "$HERE/../utils"

performreset() {

  git restore srv/main.cds
  rm -f .cdsrc.json

}

main() {

  cd "$HERE" || die "Cannot change dir to '$HERE'"
  performreset

}

main "$@"
