#!/usr/bin/env bash

set -o pipefail

HERE="$(dirname "$0")"
source "$HERE/../utils"

performreset() {

  rm -rf \
    node_modules/ \
    package-lock.json

  echo > ~/.cds-msg-box
  echo > ~/.cds-services.json

}

main() {

  cd "$HERE" || die "Cannot change dir to '$HERE'"
  performreset

}

main "$@"
