#!/usr/bin/env bash

declare PORT=4006

clearmsgbox() {
  echo > "$HOME/.cds-msg-box"
}

monmsgbox() {
  watch cat "$HOME/.cds-msg-box"
}

clearservices() {
  echo > "$HOME/.cds-services.json"
}

monservices() {
  watch -c jq -C . "$HOME/.cds-services.json"
}

sendaction() {

  local port="$PORT"
  data="${1:-$(date +%s)}" # fallback to timestamp

  curl \
    --request POST \
    --url "localhost:$port/rest/emitter/greet" \
    --data '{"greeting":"'"${data}"'"}'
}

main() {

  local util=$1
  shift
  if [[ -z $util ]]; then
    declare -F | sed 's/^declare -f //'
  else
    "$util" "$@"
  fi

}

main "$@"
