#!/usr/bin/env bash

set -o pipefail

HERE="$(dirname "$0")"
source "$HERE/../utils"

performreset() {

  rm -rf \
    ~/.cds-services.json \
    northbreeze.edmx \
    package-lock.json \
    node_modules/ \
    db/ srv/
  git restore \
    .srv/ \
    package.json

}

main() {

  cd "$HERE" || die "Cannot change dir to '$HERE'"
  performreset

}

main "$@"
