#!/usr/bin/env bash

set -o pipefail

HERE="$(dirname "$0")"
source "$HERE/../utils"

performreset() {

  rm -f ~/.cds-services.json
  rm -f northbreeze.edmx
  rm -rf db/ srv/
  git restore .srv/ package.json

}

main() {

  cd "$HERE" || die "Cannot change dir to '$HERE'"
  performreset

}

main "$@"
