#!/usr/bin/env bash

set -o pipefail

source '../utils'

performreset() {

  rm -f ~/.cds-services.json
  rm -f northbreeze.edmx
  rm -rf db/ srv/
  git restore .srv/ package.json

}

main() {

  set-dir
  performreset

}

main "$@"
