#!/usr/bin/env bash

declare NORTHBREEZE="https://developer-challenge.cfapps.eu10.hana.ondemand.com/odata/v4/northbreeze"
#declare NORTHBREEZE="http://localhost:4006/northbreeze"

getapidef() {
  curl \
    --silent \
    --url "$NORTHBREEZE/\$metadata" \
    > northbreeze.edmx
}

getproductsdata() {
  mkdir -p db/data/ \
    && curl \
      --silent \
      --url "$NORTHBREEZE/Products" \
    | jq .value \
      > "db/data/northbreeze.Products.json"
}

main() {

  local util=$1
  shift
  if [[ -z $util ]]; then
    declare -F | sed 's/^declare -f //' | grep -v main
  else
    "$util" "$@"
  fi

}

main "$@"
