#!/usr/bin/env bash

set -o pipefail

HERE="$(dirname "$0")"
source "$HERE/../utils"

setupscreen() {

  set-tmux

  # +-MAIN-(data)---------------------+
  # | lf            1| cds watch     3|
  # | to show        |                |
  # | proj files     |                |
  # +----------------+----------------+
  # | nvim          2| prompt        4|
  # | showing        | for demo       |
  # | srv/main.cds   | commands       |
  # +---------------------------------+

  tmux \
    new-window -n MAIN \; \
    split-window -h -c "#{pane_current_path}" \; \
    select-pane -t 1 \; \
    split-window -v -l 50% \; \
    select-pane -t 3 \; \
    split-window -v -l 50% \;

  tmux \
    select-pane -t 1 \; send-keys "watch -c tree -C -F -I setup -I reset" C-m \; \
    select-pane -t 2 \; send-keys "nvim srv/main.cds" C-m \; \
    select-pane -t 3 \; send-keys "cds watch" C-m \; \
    select-pane -t 4 \;

  tmux \
    select-window -t 1 \;

}

main() {

  cd "$HERE" || die "Cannot change dir to '$HERE'"
  ./reset
  set-tmux
  setupscreen
  splash

}

main "$@"
